//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietsudungtb
    {
        public string id_datphong { get; set; }
        public string id_thietbi { get; set; }
        public Nullable<System.DateTime> ngay_thue { get; set; }
        public Nullable<int> so_luong { get; set; }
        public Nullable<double> tong_tien_tb { get; set; }
    
        public virtual datphong datphong { get; set; }
        public virtual thietbi thietbi { get; set; }
    }
}
