//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datphong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public datphong()
        {
            this.chitietsudungdvs = new HashSet<chitietsudungdv>();
            this.chitietsudungtbs = new HashSet<chitietsudungtb>();
        }
    
        public string id_datphong { get; set; }
        public string id_nhanvien { get; set; }
        public string id_khachhang { get; set; }
        public string id_phong { get; set; }
        public System.DateTime check_in { get; set; }
        public Nullable<System.DateTime> check_out { get; set; }
        public Nullable<double> dat_coc { get; set; }
        public Nullable<double> tien_phong { get; set; }
        public Nullable<double> phu_thu_checkin { get; set; }
        public Nullable<double> phu_thu_checkout { get; set; }
        public Nullable<double> tong_tien_dv { get; set; }
        public Nullable<double> tong_tien_tb { get; set; }
        public Nullable<double> tong_tien_hoa_don { get; set; }
        public Nullable<double> tong_tien { get; set; }
        public Nullable<int> so_nguoi_o { get; set; }
        public string loai { get; set; }
        public string trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietsudungdv> chitietsudungdvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietsudungtb> chitietsudungtbs { get; set; }
        public virtual khachhang khachhang { get; set; }
        public virtual nhanvien nhanvien { get; set; }
        public virtual phong phong { get; set; }
    }
}
