//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class imgphong
    {
        public int id_loaiphong { get; set; }
        public string id_hinh { get; set; }
    
        public virtual loaiphong loaiphong { get; set; }
    }
}
