//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phong()
        {
            this.datphongs = new HashSet<datphong>();
            this.datphongonlines = new HashSet<datphongonline>();
        }
    
        public string id_phong { get; set; }
        public int id_loaiphong { get; set; }
        public int id_tang { get; set; }
        public string ten { get; set; }
        public string trang_thai { get; set; }
        public int gia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datphong> datphongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datphongonline> datphongonlines { get; set; }
        public virtual loaiphong loaiphong { get; set; }
        public virtual tang tang { get; set; }
    }
}
