//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDatPhongKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taikhoan
    {
        public int id_taikhoan { get; set; }
        public string id_nhanvien { get; set; }
        public string ten_dang_nhap { get; set; }
        public string mat_khau { get; set; }
        public Nullable<int> hoat_dong { get; set; }
        public string quyen { get; set; }
    
        public virtual nhanvien nhanvien { get; set; }
    }
}
